#Linux :
    before                          [在main函数之前挂载函数]
    structField                     [根据结构体内的字段获取对应的值]
    show_bytes                      [深入操作系统-查看类型地址]
    printf_define                   [格式化输出宏修改 与 长度变长]
    vlog                            [动态库加载日志模块]
    dynamicStructArrt               [动态结构数组]
    sizeofStructIsCore              [结构体数据求sizeof会不会core]
    GetValueOfDomain                [从字符串中根据分隔符获取对应域的值]
    TestReturnCore                  [函数测试返回时报core问题]
    Test=+Gcc                       [测试Gcc编译时 =+ 是否报错]
    cgroup_cpu                      [测试cgroup, 利用cgroup关cpu使用高的小黑屋(借鉴容器的核心设计)]
    cgroup_mem                      [强行占用内存900M , 测试内存限制 cgroup]
    CaptchaGenerator                [C语言编写的验证码生成器,支持纯数字、数字加字母大小写的7种组合, 稍微修改一下就可以变成密码随机生成器]
    Many2OneMapping                 [多对一映射,脱离数据库实现的后端多返回码映射成指定一个返回码]
#Windows:
    returnCore                      [函数测试返回时报core问题]
